spring.application.name=Studentcrudapp
spring.datasource.url=jdbc:mysql://localhost:3306/studentsdb
spring.datasource.username=root
spring.datasource.password=Hema123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true